---
- name: Create grafana persistent directory
  file:
    path: "{{ GRAFANA_DIR }}"
    state: directory
    mode: 0755

- name: Start grafana docker container
  docker_container:
    name: grafana
    image: grafana/grafana
    ports:
      - "127.0.0.1:{{ GRAFANA_PORT }}:{{ GRAFANA_PORT }}"
    volumes:
      - "{{ GRAFANA_DIR }}:{{ GRAFANA_DIR }}"
    restart_policy: unless-stopped
    env:
      GF_SERVER_HTTP_PORT="{{ GRAFANA_PORT }}"
  notify: restart nginx
